global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django-app'
    kubernetes_sd_configs:
    - role: endpoints
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: django-app-service
